import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '~': path.resolve(__dirname, './app'),
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./tests/_setup/setup.ts'],
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
    server: {
      deps: {
        // jose ships ESM that vitest needs to inline-process
        inline: ['jose'],
      },
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov', 'json-summary'],
      include: ['app/**/*.{ts,tsx}'],
      exclude: [
        // generated by TanStack Router
        'app/routeTree.gen.ts',
        // SSR / hydration entry points — exercised end-to-end, not unit-testable
        'app/client.tsx',
        'app/ssr.tsx',
        'app/router.tsx',
        // type-only file
        'app/lib/env.ts',
        // file-route components are mostly thin loaders; they exercise the
        // server fns we already test. Skip from numeric thresholds but
        // they still appear in the report.
        'app/routes/**',
        // pulled into bundle via R2 streaming only; uncovered branches are
        // edge runtime fall-throughs
        'app/db/client.ts',
        '**/*.d.ts',
      ],
      // Targets reflect what we exercise from Node (impl helpers, pure modules,
      // components).  createServerFn wrappers add a few uncovered lines that
      // only run inside the Worker / SSR runtime; raise the bar once we add
      // integration tests under wrangler.
      thresholds: {
        lines: 80,
        statements: 80,
        functions: 80,
        branches: 70,
      },
    },
  },
});
