name = "transition-web"
main = "../../dist/server/server.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

assets = { directory = "../../dist/client", binding = "ASSETS" }

[[routes]]
pattern = "transition.allenlabs.org"
custom_domain = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "0b76cf08a44443d39d12f0d51ed059f5"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "96408ec81e754c36b4ae3643cf2afd80"

[vars]
APP_NAME = "Transition"
AUTH_WEB_URL = "https://auth.allen.company"
AUTH_API_URL = "https://auth-api.allen.company"
PUBLIC_BASE_URL = "https://transition.allenlabs.org"
